CREATE TABLE `dht` (
	`Hash` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(200) NOT NULL,
	`Description` MEDIUMTEXT NULL,
	`Updatetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Rank` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Hash`),
	UNIQUE INDEX `Hash` (`Hash`),
	UNIQUE INDEX `Id` (`Id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1889;

CREATE TABLE `sph_counter` (
	`counter_id` INT(11) NOT NULL,
	`max_doc_id` INT(11) NOT NULL,
	PRIMARY KEY (`counter_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

